class Category {
  int id;

  String name;

  String imageUrl;

  Category({required this.id, required this.name, required this.imageUrl});
}

List<Category> categoryList = [
  Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""),
  Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""),
  Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""),
  Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""), Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""),
  Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""), Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""),
  Category(id: 1,name: "New Product",imageUrl: ""),
  Category(id: 1,name: "Special offers",imageUrl: ""),
  Category(id: 1,name: "Water",imageUrl: ""),
  Category(id: 1,name: "Bevreges",imageUrl: ""),
  Category(id: 1,name: "Fruites & Veg",imageUrl: ""),
  Category(id: 1,name: "Baked Goods",imageUrl: ""),
  Category(id: 1,name: "Food",imageUrl: ""),
  Category(id: 1,name: "Snacks",imageUrl: ""),
];